// Configuração de todas as moedas do CashSum.
// A chave do objeto é usada como slug do URL: cashsum.app/[slug]

export const CURRENCIES = {
  eur: {
    nome: "Euro (€)",
    bandeira: "🇪🇺",
    flagCode: "eu",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "en",
    pageTitle: "Euro Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the Euro",
      paragraphs: [
        "The euro became an official currency in 1999, but it stayed invisible for three years, used only for electronic accounting while national currencies like the French franc and German mark remained in people's pockets. Physical notes and coins only entered circulation on 1 January 2002, when they quickly replaced twelve national currencies across the newly formed eurozone. Since then, the eurozone has kept growing, most recently welcoming Bulgaria on 1 January 2026.",
        "Euro banknotes come in seven denominations: €5, €10, €20, €50, €100, €200 and €500, though the €500 note stopped being issued in 2019 over concerns it made illicit transactions too easy. Every note shares the same design across all member countries, showing windows and doorways on the front and bridges on the back, symbolizing openness and connection rather than any single nation's landmarks. Coins are different: each country mints its own design on one side, while the reverse stays common to the whole currency union.",
        "A small but clever detail: the 20 cent coin has seven scalloped edges, shaped like a rounded flower, so people can recognize it by touch alone even in a dark pocket or wallet. Euro coins are also designed to resist melting down for their metal value, and vending machines and cash counters use their weight and magnetic properties to sort them automatically, the same logic this calculator relies on to help you count your euros in seconds.",
      ],
    },
  },
  "euro-de": {
    nome: "Euro (€) — Deutschland",
    bandeira: "🇩🇪",
    flagCode: "de",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "de",
    hidden: true,
    pageTitle: "Euro Geldzähler",
    tagline: "Zählen Sie Ihre Scheine und Münzen in Sekunden",
    description:
      "Wählen Sie die Währung, geben Sie ein, wie viele Scheine und Münzen Sie haben, und sehen Sie die Summe sofort.",
    searchTerm: "geldzähler / bargeldrechner",
    ui: {
      coins: "Münzen",
      notes: "Scheine",
      total: "Gesamt",
      clear: "Alles löschen",
      coinsSub: "Zwischensumme Münzen",
      notesSub: "Zwischensumme Scheine",
      footer: "zählen Sie Ihr Geld in Sekunden",
    },
    article: {
      heading: "Über den Euro",
      paragraphs: [
        "Der Euro wurde 1999 offiziell eingeführt, blieb aber drei Jahre lang unsichtbar und diente nur der elektronischen Buchhaltung, während nationale Währungen wie der französische Franc und die deutsche Mark weiterhin im Umlauf waren. Scheine und Münzen kamen erst am 1. Januar 2002 in Umlauf und ersetzten innerhalb kurzer Zeit zwölf nationale Währungen in der neu gegründeten Eurozone. Seitdem ist die Eurozone stetig gewachsen, zuletzt mit dem Beitritt Bulgariens am 1. Januar 2026.",
        "Euro-Banknoten gibt es in sieben Stückelungen: 5€, 10€, 20€, 50€, 100€, 200€ und 500€ — wobei der 500-Euro-Schein seit 2019 nicht mehr ausgegeben wird, da er zu häufig für illegale Geschäfte genutzt wurde. Jeder Schein hat in allen Mitgliedsländern das gleiche Design, mit Fenstern und Toren auf der Vorderseite und Brücken auf der Rückseite — ein Symbol für Offenheit und Verbindung statt nationaler Wahrzeichen. Bei den Münzen ist es anders: jedes Land prägt seine eigene nationale Seite, während die Rückseite für die gesamte Währungsunion einheitlich bleibt.",
        "Ein kleines, cleveres Detail: Die 20-Cent-Münze hat sieben abgerundete Kerben, geformt wie eine Blume, damit man sie allein durch Ertasten erkennen kann, selbst in einer dunklen Hosentasche. Euromünzen sind zudem so gestaltet, dass sie sich schwer einschmelzen lassen, und Geldzählmaschinen erkennen sie anhand von Gewicht und magnetischen Eigenschaften — genau das Prinzip, das auch dieser Rechner nutzt, um Ihr Geld in Sekunden zu zählen.",
      ],
    },
  },
  "euro-fr": {
    nome: "Euro (€) — France",
    bandeira: "🇫🇷",
    flagCode: "fr",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "fr",
    hidden: true,
    pageTitle: "Compteur d'euros",
    tagline: "Comptez vos billets et pièces en quelques secondes",
    description:
      "Choisissez la devise, indiquez combien de billets et de pièces vous avez, et voyez le total instantanément.",
    searchTerm: "compteur d'argent / compteur de pièces",
    ui: {
      coins: "Pièces",
      notes: "Billets",
      total: "Total",
      clear: "Tout effacer",
      coinsSub: "Sous-total pièces",
      notesSub: "Sous-total billets",
      footer: "comptez votre argent en quelques secondes",
    },
    article: {
      heading: "À propos de l'euro",
      paragraphs: [
        "L'euro est devenu une monnaie officielle en 1999, mais il est resté invisible pendant trois ans, utilisé uniquement pour la comptabilité électronique pendant que des monnaies nationales comme le franc français et le mark allemand circulaient encore. Les billets et pièces ne sont entrés en circulation que le 1er janvier 2002, remplaçant rapidement douze monnaies nationales dans la toute nouvelle zone euro. Depuis, la zone euro n'a cessé de s'agrandir, avec l'arrivée la plus récente de la Bulgarie le 1er janvier 2026.",
        "Les billets en euros existent en sept coupures : 5€, 10€, 20€, 50€, 100€, 200€ et 500€, ce dernier n'étant plus émis depuis 2019 en raison de son usage jugé trop facile pour des transactions illicites. Chaque billet a le même design dans tous les pays membres, avec des fenêtres et des portes à l'avant et des ponts au dos, symbolisant l'ouverture et la connexion plutôt que les monuments d'un pays en particulier. Les pièces sont différentes : chaque pays y grave son propre motif national, tandis que le revers reste commun à toute l'union monétaire.",
        "Un petit détail astucieux : la pièce de 20 centimes a sept bords arrondis en forme de fleur, permettant de la reconnaître au toucher, même dans une poche sombre. Les pièces en euros sont aussi conçues pour résister à la fonte, et les compteurs d'argent ainsi que les distributeurs automatiques utilisent leur poids et leurs propriétés magnétiques pour les trier automatiquement — le même principe que cet outil utilise pour compter vos euros en quelques secondes.",
      ],
    },
  },
  "euro-es": {
    nome: "Euro (€) — España",
    bandeira: "🇪🇸",
    flagCode: "es",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "es",
    hidden: true,
    pageTitle: "Contador de Euros",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, indica cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero / contador de monedas",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
    article: {
      heading: "Sobre el Euro",
      paragraphs: [
        "El euro se convirtió en moneda oficial en 1999, pero permaneció invisible durante tres años, usado solo para contabilidad electrónica mientras monedas nacionales como el franco francés y el marco alemán seguían circulando. Los billetes y monedas físicos no entraron en circulación hasta el 1 de enero de 2002, cuando reemplazaron rápidamente a doce monedas nacionales en la recién creada zona euro. Desde entonces, la zona euro no ha dejado de crecer, con la incorporación más reciente de Bulgaria el 1 de enero de 2026.",
        "Los billetes de euro existen en siete denominaciones: 5€, 10€, 20€, 50€, 100€, 200€ y 500€, aunque este último dejó de emitirse en 2019 por su uso asociado a actividades ilícitas. Cada billete comparte el mismo diseño en todos los países miembros, con ventanas y puertas en el anverso y puentes en el reverso, simbolizando apertura y conexión en lugar de monumentos de un país concreto. Las monedas son distintas: cada país acuña su propio diseño nacional en una cara, mientras que el reverso es común a toda la unión monetaria.",
        "Un pequeño detalle ingenioso: la moneda de 20 céntimos tiene siete bordes redondeados en forma de flor, lo que permite reconocerla al tacto incluso dentro de un bolsillo oscuro. Las monedas de euro también están diseñadas para resistir la fundición, y las máquinas contadoras y expendedoras usan su peso y propiedades magnéticas para clasificarlas automáticamente, el mismo principio que utiliza esta calculadora para contar tus euros en segundos.",
      ],
    },
  },
  "euro-it": {
    nome: "Euro (€) — Italia",
    bandeira: "🇮🇹",
    flagCode: "it",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "it",
    hidden: true,
    pageTitle: "Contatore di Euro",
    tagline: "Conta le tue banconote e monete in pochi secondi",
    description:
      "Scegli la valuta, indica quante banconote e monete hai, e vedi il totale all'istante.",
    searchTerm: "contatore di denaro / conta monete",
    ui: {
      coins: "Monete",
      notes: "Banconote",
      total: "Totale",
      clear: "Cancella tutto",
      coinsSub: "Subtotale monete",
      notesSub: "Subtotale banconote",
      footer: "conta i tuoi soldi in pochi secondi",
    },
    article: {
      heading: "Informazioni sull'Euro",
      paragraphs: [
        "L'euro è diventato una valuta ufficiale nel 1999, ma è rimasto invisibile per tre anni, usato solo per la contabilità elettronica mentre le valute nazionali come il franco francese e il marco tedesco erano ancora in circolazione. Banconote e monete sono entrate in circolazione solo il 1° gennaio 2002, sostituendo rapidamente dodici valute nazionali nella neonata area euro. Da allora l'area euro ha continuato a crescere, con l'ingresso più recente della Bulgaria il 1° gennaio 2026.",
        "Le banconote in euro esistono in sette tagli: 5€, 10€, 20€, 50€, 100€, 200€ e 500€, anche se quest'ultimo non viene più emesso dal 2019 per timori legati a un uso troppo facile in transazioni illecite. Ogni banconota ha lo stesso design in tutti i paesi membri, con finestre e portali sul fronte e ponti sul retro, a simboleggiare apertura e connessione piuttosto che i monumenti di un singolo paese. Le monete sono diverse: ogni paese conia il proprio disegno nazionale su un lato, mentre il retro resta comune a tutta l'unione monetaria.",
        "Un piccolo dettaglio intelligente: la moneta da 20 centesimi ha sette bordi smussati a forma di fiore, così da poterla riconoscere al tatto anche in una tasca buia. Le monete in euro sono anche progettate per resistere alla fusione, e i contatori di denaro e i distributori automatici usano il loro peso e le proprietà magnetiche per smistarle automaticamente — lo stesso principio su cui si basa questo strumento per contare i tuoi euro in pochi secondi.",
      ],
    },
  },
  "euro-nl": {
    nome: "Euro (€) — Nederland",
    bandeira: "🇳🇱",
    flagCode: "nl",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "nl",
    hidden: true,
    pageTitle: "Euro Geldteller",
    tagline: "Tel je briefjes en munten in seconden",
    description:
      "Kies de valuta, geef aan hoeveel briefjes en munten je hebt, en zie direct het totaal.",
    searchTerm: "geldteller / muntenteller",
    ui: {
      coins: "Munten",
      notes: "Briefjes",
      total: "Totaal",
      clear: "Alles wissen",
      coinsSub: "Subtotaal munten",
      notesSub: "Subtotaal briefjes",
      footer: "tel je geld in seconden",
    },
    article: {
      heading: "Over de Euro",
      paragraphs: [
        "De euro werd in 1999 een officiële munt, maar bleef drie jaar lang onzichtbaar en werd alleen gebruikt voor elektronische administratie, terwijl nationale valuta's zoals de Franse frank en de Duitse mark nog in omloop waren. Pas op 1 januari 2002 kwamen bankbiljetten en munten in omloop, waarmee twaalf nationale valuta's in de eurozone snel werden vervangen. Sindsdien is de eurozone blijven groeien, met Bulgarije als meest recente lid sinds 1 januari 2026. Er zijn zeven coupures: €5, €10, €20, €50, €100, €200 en €500, al wordt dat laatste biljet sinds 2019 niet meer uitgegeven vanwege het risico op illegaal gebruik.",
        "Een slim detail: het muntstuk van 20 cent heeft zeven afgeronde randen in de vorm van een bloem, zodat je het op de tast kunt herkennen, zelfs in een donkere zak. Euromunten zijn ook ontworpen om moeilijk om te smelten te zijn, en geldtellers herkennen ze op gewicht en magnetische eigenschappen — precies het principe waarop deze rekenmachine is gebaseerd.",
      ],
    },
  },
  "euro-pt": {
    nome: "Euro (€) — Portugal",
    bandeira: "🇵🇹",
    flagCode: "pt",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "pt-PT",
    hidden: true,
    pageTitle: "Contador de Euros",
    tagline: "Conta as tuas notas e moedas em segundos",
    description:
      "Escolhe a moeda, indica quantas notas e moedas tens, e vê o total na hora.",
    searchTerm: "contador de dinheiro / contador de moedas",
    ui: {
      coins: "Moedas",
      notes: "Notas",
      total: "Total",
      clear: "Limpar tudo",
      coinsSub: "Subtotal moedas",
      notesSub: "Subtotal notas",
      footer: "conta o teu dinheiro em segundos",
    },
    article: {
      heading: "Sobre o Euro",
      paragraphs: [
        "O euro tornou-se moeda oficial em 1999, mas manteve-se invisível durante três anos, usado só para contabilidade eletrónica enquanto moedas nacionais como o franco francês e o marco alemão continuavam em circulação. As notas e moedas físicas só entraram em circulação a 1 de janeiro de 2002, substituindo rapidamente doze moedas nacionais na recém-criada zona euro. Desde então, a zona euro não parou de crescer, com a Bulgária a juntar-se mais recentemente, a 1 de janeiro de 2026. Existem sete denominações de notas: 5€, 10€, 20€, 50€, 100€, 200€ e 500€, sendo que esta última deixou de ser emitida em 2019 devido ao receio de facilitar transações ilícitas.",
        "Um pormenor engenhoso: a moeda de 20 cêntimos tem sete bordos arredondados em forma de flor, o que permite reconhecê-la ao tato mesmo num bolso escuro. As moedas de euro também são feitas para resistir à fundição, e as máquinas contadoras usam o peso e as propriedades magnéticas para as identificar automaticamente — o mesmo princípio usado por esta calculadora.",
      ],
    },
  },
  "euro-el": {
    nome: "Euro (€) — Ελλάδα",
    bandeira: "🇬🇷",
    flagCode: "gr",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "el",
    hidden: true,
    pageTitle: "Μετρητής Ευρώ",
    tagline: "Μετρήστε τα χαρτονομίσματα και τα κέρματά σας σε δευτερόλεπτα",
    description:
      "Επιλέξτε το νόμισμα, εισαγάγετε πόσα χαρτονομίσματα και κέρματα έχετε, και δείτε αμέσως το σύνολο.",
    searchTerm: "μετρητής χρημάτων / μετρητής κερμάτων",
    ui: {
      coins: "Κέρματα",
      notes: "Χαρτονομίσματα",
      total: "Σύνολο",
      clear: "Καθαρισμός όλων",
      coinsSub: "Υποσύνολο κερμάτων",
      notesSub: "Υποσύνολο χαρτονομισμάτων",
      footer: "μετρήστε τα χρήματά σας σε δευτερόλεπτα",
    },
    article: {
      heading: "Σχετικά με το Ευρώ",
      paragraphs: [
        "Το ευρώ έγινε επίσημο νόμισμα το 1999, αλλά παρέμεινε αόρατο για τρία χρόνια, χρησιμοποιούμενο μόνο για ηλεκτρονική λογιστική, ενώ εθνικά νομίσματα όπως το γαλλικό φράγκο και το γερμανικό μάρκο ήταν ακόμη σε κυκλοφορία. Τα χαρτονομίσματα και τα κέρματα κυκλοφόρησαν μόλις την 1η Ιανουαρίου 2002, αντικαθιστώντας γρήγορα δώδεκα εθνικά νομίσματα στη νεοσύστατη ευρωζώνη. Από τότε η ευρωζώνη συνεχίζει να μεγαλώνει, με πιο πρόσφατο μέλος τη Βουλγαρία από την 1η Ιανουαρίου 2026. Υπάρχουν επτά ονομαστικές αξίες χαρτονομισμάτων: 5€, 10€, 20€, 50€, 100€, 200€ και 500€, με το τελευταίο να μην εκδίδεται πλέον από το 2019 λόγω ανησυχιών για παράνομες συναλλαγές.",
        "Μια έξυπνη λεπτομέρεια: το κέρμα των 20 λεπτών έχει επτά στρογγυλεμένες άκρες σε σχήμα λουλουδιού, ώστε να αναγνωρίζεται με την αφή ακόμη και μέσα σε μια σκοτεινή τσέπη. Τα κέρματα ευρώ είναι επίσης σχεδιασμένα να αντιστέκονται στην τήξη, και οι μετρητές χρημάτων τα αναγνωρίζουν από το βάρος και τις μαγνητικές τους ιδιότητες — ακριβώς η αρχή στην οποία βασίζεται αυτό το εργαλείο.",
      ],
    },
  },
  "euro-fi": {
    nome: "Euro (€) — Suomi",
    bandeira: "🇫🇮",
    flagCode: "fi",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "fi",
    hidden: true,
    pageTitle: "Euron Rahalaskuri",
    tagline: "Laske setelisi ja kolikkosi sekunneissa",
    description:
      "Valitse valuutta, syötä kuinka monta seteliä ja kolikkoa sinulla on, ja näe summa heti.",
    searchTerm: "rahanlaskija / kolikkolaskuri",
    ui: {
      coins: "Kolikot",
      notes: "Setelit",
      total: "Yhteensä",
      clear: "Tyhjennä kaikki",
      coinsSub: "Kolikoiden välisumma",
      notesSub: "Seteleiden välisumma",
      footer: "laske rahasi sekunneissa",
    },
    article: {
      heading: "Tietoa Eurosta",
      paragraphs: [
        "Eurosta tuli virallinen valuutta vuonna 1999, mutta se pysyi näkymättömänä kolme vuotta ja sitä käytettiin vain sähköiseen kirjanpitoon, kun kansalliset valuutat, kuten Ranskan frangi ja Saksan markka, olivat vielä käytössä. Setelit ja kolikot tulivat käyttöön vasta 1. tammikuuta 2002, jolloin ne korvasivat nopeasti kaksitoista kansallista valuuttaa vastaperustetulla euroalueella. Siitä lähtien euroalue on kasvanut jatkuvasti, ja tuorein jäsen on Bulgaria 1. tammikuuta 2026 alkaen. Seteleitä on seitsemän arvoa: 5€, 10€, 20€, 50€, 100€, 200€ ja 500€, joista viimeksi mainittua ei enää painateta vuodesta 2019 alkaen, koska sen pelättiin helpottavan laittomia liiketoimia.",
        "Nokkela yksityiskohta: 20 sentin kolikossa on seitsemän pyöristettyä reunaa kukan muodossa, jotta sen tunnistaa tunnustelemalla pimeässäkin taskussa. Eurokolikot on myös suunniteltu kestämään sulattamista, ja rahanlaskukoneet tunnistavat ne painon ja magneettisten ominaisuuksien perusteella — sama periaate, johon tämäkin laskuri perustuu.",
      ],
    },
  },
  "euro-sk": {
    nome: "Euro (€) — Slovensko",
    bandeira: "🇸🇰",
    flagCode: "sk",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "sk",
    hidden: true,
    pageTitle: "Počítačka Eur",
    tagline: "Spočítajte svoje bankovky a mince za pár sekúnd",
    description:
      "Vyberte menu, zadajte, koľko bankoviek a mincí máte, a okamžite uvidíte celkovú sumu.",
    searchTerm: "počítačka peňazí / počítačka mincí",
    ui: {
      coins: "Mince",
      notes: "Bankovky",
      total: "Spolu",
      clear: "Vymazať všetko",
      coinsSub: "Medzisúčet mincí",
      notesSub: "Medzisúčet bankoviek",
      footer: "spočítajte svoje peniaze za pár sekúnd",
    },
    article: {
      heading: "O eure",
      paragraphs: [
        "Euro sa stalo oficiálnou menou v roku 1999, no tri roky zostávalo neviditeľné a používalo sa iba na elektronické účtovníctvo, zatiaľ čo národné meny ako francúzsky frank či nemecká marka boli stále v obehu. Bankovky a mince sa do obehu dostali až 1. januára 2002, keď rýchlo nahradili dvanásť národných mien v novovzniknutej eurozóne. Odvtedy eurozóna neustále rastie, naposledy sa k nej pripojilo Bulharsko 1. januára 2026. V obehu je sedem nominálnych hodnôt bankoviek: 5€, 10€, 20€, 50€, 100€, 200€ a 500€, pričom posledná menovaná sa od roku 2019 už netlačí pre obavy z uľahčenia nezákonných transakcií.",
        "Šikovný detail: minca v hodnote 20 centov má sedem zaoblených hrán v tvare kvetu, takže ju možno rozpoznať hmatom aj v tmavom vrecku. Eurové mince sú tiež navrhnuté tak, aby odolávali roztaveniu, a počítačky peňazí ich rozpoznávajú podľa hmotnosti a magnetických vlastností — presne na tomto princípe funguje aj táto kalkulačka.",
      ],
    },
  },
  "euro-sl": {
    nome: "Euro (€) — Slovenija",
    bandeira: "🇸🇮",
    flagCode: "si",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "sl",
    hidden: true,
    pageTitle: "Števec Eurov",
    tagline: "Preštejte svoje bankovce in kovance v nekaj sekundah",
    description:
      "Izberite valuto, vnesite, koliko bankovcev in kovancev imate, in takoj vidite skupni znesek.",
    searchTerm: "štetje denarja / štetje kovancev",
    ui: {
      coins: "Kovanci",
      notes: "Bankovci",
      total: "Skupaj",
      clear: "Počisti vse",
      coinsSub: "Vmesna vsota kovancev",
      notesSub: "Vmesna vsota bankovcev",
      footer: "preštejte svoj denar v nekaj sekundah",
    },
    article: {
      heading: "O evru",
      paragraphs: [
        "Evro je postal uradna valuta leta 1999, vendar je tri leta ostal neviden in se je uporabljal le za elektronsko knjigovodstvo, medtem ko so bile nacionalne valute, kot sta francoski frank in nemška marka, še vedno v obtoku. Bankovci in kovanci so v obtok prišli šele 1. januarja 2002, ko so hitro nadomestili dvanajst nacionalnih valut v na novo ustanovljenem euroobmočju. Od takrat euroobmočje nenehno raste, najnovejša članica pa je Bolgarija od 1. januarja 2026. V obtoku je sedem apoenov bankovcev: 5€, 10€, 20€, 50€, 100€, 200€ in 500€, pri čemer se zadnji od leta 2019 ne izdaja več zaradi bojazni pred lažjo uporabo pri nezakonitih poslih.",
        "Zvit podrobnost: kovanec za 20 centov ima sedem zaobljenih robov v obliki cvetlice, tako da ga lahko prepoznate zgolj na otip, tudi v temnem žepu. Evro kovanci so zasnovani tudi tako, da se jih težko stopi, števci denarja pa jih prepoznajo po teži in magnetnih lastnostih — po enakem načelu deluje tudi ta kalkulator.",
      ],
    },
  },
  "euro-hr": {
    nome: "Euro (€) — Hrvatska",
    bandeira: "🇭🇷",
    flagCode: "hr",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "hr",
    hidden: true,
    pageTitle: "Brojač Eura",
    tagline: "Izbrojite svoje novčanice i kovanice u nekoliko sekundi",
    description:
      "Odaberite valutu, unesite koliko novčanica i kovanica imate, i odmah vidite ukupan iznos.",
    searchTerm: "brojač novca / brojač kovanica",
    ui: {
      coins: "Kovanice",
      notes: "Novčanice",
      total: "Ukupno",
      clear: "Obriši sve",
      coinsSub: "Međuzbroj kovanica",
      notesSub: "Međuzbroj novčanica",
      footer: "izbrojite svoj novac u nekoliko sekundi",
    },
    article: {
      heading: "O euru",
      paragraphs: [
        "Euro je postao službena valuta 1999. godine, no tri je godine ostao nevidljiv, koristeći se samo za elektroničko knjigovodstvo dok su nacionalne valute poput francuskog franka i njemačke marke i dalje bile u optjecaju. Novčanice i kovanice ušle su u optjecaj tek 1. siječnja 2002., brzo zamijenivši dvanaest nacionalnih valuta u novoosnovanoj eurozoni. Otada eurozona neprestano raste, a najnovija članica je Bugarska od 1. siječnja 2026. U optjecaju je sedam apoena novčanica: 5€, 10€, 20€, 50€, 100€, 200€ i 500€, s tim da se posljednja od 2019. više ne izdaje zbog bojazni da olakšava nezakonite transakcije.",
        "Pametan detalj: kovanica od 20 centi ima sedam zaobljenih rubova u obliku cvijeta, kako bi se mogla prepoznati opipom čak i u mračnom džepu. Kovanice eura također su dizajnirane da se teško tale, a brojači novca ih prepoznaju prema težini i magnetskim svojstvima — na istom načelu radi i ovaj kalkulator.",
      ],
    },
  },
  "euro-et": {
    nome: "Euro (€) — Eesti",
    bandeira: "🇪🇪",
    flagCode: "ee",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "et",
    hidden: true,
    pageTitle: "Euro Rahaloendaja",
    tagline: "Loenda oma pangatähed ja mündid sekunditega",
    description:
      "Vali valuuta, sisesta, mitu pangatähte ja münti sul on, ning näe kohe kogusummat.",
    searchTerm: "rahaloendaja / mündiloendaja",
    ui: {
      coins: "Mündid",
      notes: "Pangatähed",
      total: "Kokku",
      clear: "Tühjenda kõik",
      coinsSub: "Müntide vahesumma",
      notesSub: "Pangatähtede vahesumma",
      footer: "loenda oma raha sekunditega",
    },
    article: {
      heading: "Eurost lähemalt",
      paragraphs: [
        "Euro sai ametlikuks valuutaks 1999. aastal, kuid jäi kolmeks aastaks nähtamatuks ja seda kasutati vaid elektroonilises raamatupidamises, samal ajal kui riiklikud valuutad nagu Prantsuse frank ja Saksa mark olid endiselt käibel. Pangatähed ja mündid tulid käibele alles 1. jaanuaril 2002, asendades kiiresti kaksteist riiklikku valuutat äsjaloodud euroalal. Sellest ajast on euroala pidevalt kasvanud, kõige uuem liige on Bulgaaria alates 1. jaanuarist 2026. Käibel on seitse pangatähe nimiväärtust: 5€, 10€, 20€, 50€, 100€, 200€ ja 500€, millest viimast ei ole alates 2019. aastast enam trükitud, kartuses, et see hõlbustab ebaseaduslikke tehinguid.",
        "Nutikas detail: 20-sendisel mündil on seitse ümarat serva lillekujuliselt, et seda saaks katsudes ära tunda ka pimedas taskus. Euromündid on ka disainitud nii, et neid on raske sulatada, ning rahaloendajad tuvastavad neid kaalu ja magnetiliste omaduste järgi — täpselt sellel põhimõttel töötab ka see kalkulaator.",
      ],
    },
  },
  "euro-lv": {
    nome: "Euro (€) — Latvija",
    bandeira: "🇱🇻",
    flagCode: "lv",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "lv",
    hidden: true,
    pageTitle: "Eiro skaitītājs",
    tagline: "Saskaitiet savas banknotes un monētas dažu sekunžu laikā",
    description:
      "Izvēlieties valūtu, ievadiet, cik banknošu un monētu jums ir, un uzreiz redziet kopsummu.",
    searchTerm: "naudas skaitītājs / monētu skaitītājs",
    ui: {
      coins: "Monētas",
      notes: "Banknotes",
      total: "Kopā",
      clear: "Notīrīt visu",
      coinsSub: "Monētu starpsumma",
      notesSub: "Banknošu starpsumma",
      footer: "saskaitiet savu naudu dažu sekunžu laikā",
    },
    article: {
      heading: "Par eiro",
      paragraphs: [
        "Eiro kļuva par oficiālu valūtu 1999. gadā, taču trīs gadus palika neredzams un tika izmantots tikai elektroniskajā uzskaitē, kamēr nacionālās valūtas, piemēram, Francijas franks un Vācijas marka, joprojām bija apgrozībā. Banknotes un monētas apgrozībā nonāca tikai 2002. gada 1. janvārī, ātri aizstājot divpadsmit nacionālās valūtas jaunizveidotajā eirozonā. Kopš tā laika eirozona nepārtraukti pieaugusi, un jaunākā dalībvalsts ir Bulgārija kopš 2026. gada 1. janvāra. Apgrozībā ir septiņi banknošu nomināli: 5€, 10€, 20€, 50€, 100€, 200€ un 500€, pēdējo no tiem kopš 2019. gada vairs neizdod bažu dēļ, ka tas atvieglo nelegālus darījumus.",
        "Gudra detaļa: 20 centu monētai ir septiņas noapaļotas malas ziedu formā, lai to varētu atpazīt pēc taustes pat tumšā kabatā. Eiro monētas ir veidotas arī tā, lai tās būtu grūti izkausēt, un naudas skaitītāji tās atpazīst pēc svara un magnētiskajām īpašībām — tieši uz šī principa balstās arī šis kalkulators.",
      ],
    },
  },
  "euro-lt": {
    nome: "Euro (€) — Lietuva",
    bandeira: "🇱🇹",
    flagCode: "lt",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "lt",
    hidden: true,
    pageTitle: "Eurų Skaičiuoklė",
    tagline: "Suskaičiuokite savo banknotus ir monetas per kelias sekundes",
    description:
      "Pasirinkite valiutą, įveskite, kiek turite banknotų ir monetų, ir iškart pamatysite bendrą sumą.",
    searchTerm: "pinigų skaičiuoklė / monetų skaičiuoklė",
    ui: {
      coins: "Monetos",
      notes: "Banknotai",
      total: "Iš viso",
      clear: "Išvalyti viską",
      coinsSub: "Monetų tarpinė suma",
      notesSub: "Banknotų tarpinė suma",
      footer: "suskaičiuokite savo pinigus per kelias sekundes",
    },
    article: {
      heading: "Apie eurą",
      paragraphs: [
        "Euras oficialia valiuta tapo 1999 metais, tačiau trejus metus liko nematomas ir buvo naudojamas tik elektroninei apskaitai, kol nacionalinės valiutos, tokios kaip Prancūzijos frankas ir Vokietijos markė, dar buvo apyvartoje. Banknotai ir monetos į apyvartą pateko tik 2002 metų sausio 1 dieną, greitai pakeisdami dvylika nacionalinių valiutų naujai sukurtoje euro zonoje. Nuo tada euro zona nuolat auga, naujausia narė — Bulgarija nuo 2026 metų sausio 1 dienos. Apyvartoje yra septyni banknotų nominalai: 5€, 10€, 20€, 50€, 100€, 200€ ir 500€, pastarojo nuo 2019 metų nebespausdinama dėl nuogąstavimų, kad jis palengvina neteisėtus sandorius.",
        "Gudrus detalė: 20 centų moneta turi septynis suapvalintus kraštus gėlės formos, todėl ją galima atpažinti liečiant net tamsioje kišenėje. Euro monetos taip pat sukurtos taip, kad jas būtų sunku išlydyti, o pinigų skaičiuoklės jas atpažįsta pagal svorį ir magnetines savybes — būtent šiuo principu remiasi ir ši skaičiuoklė.",
      ],
    },
  },
  "euro-bg": {
    nome: "Euro (€) — България",
    bandeira: "🇧🇬",
    flagCode: "bg",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "bg",
    hidden: true,
    pageTitle: "Брояч на Евро",
    tagline: "Пребройте банкнотите и монетите си за секунди",
    description:
      "Изберете валута, въведете колко банкноти и монети имате, и вижте сумата веднага.",
    searchTerm: "брояч на пари / брояч на монети",
    ui: {
      coins: "Монети",
      notes: "Банкноти",
      total: "Общо",
      clear: "Изчисти всичко",
      coinsSub: "Междинна сума монети",
      notesSub: "Междинна сума банкноти",
      footer: "пребройте парите си за секунди",
    },
    article: {
      heading: "За еврото",
      paragraphs: [
        "Еврото става официална валута през 1999 г., но остава невидимо в продължение на три години, използвано само за електронно счетоводство, докато национални валути като френския франк и германската марка все още са в обращение. Банкнотите и монетите влизат в обращение едва на 1 януари 2002 г., бързо заменяйки дванадесет национални валути в новосъздадената еврозона. Оттогава еврозоната непрекъснато расте, като най-новият член е България от 1 януари 2026 г. В обращение са седем номинала банкноти: 5€, 10€, 20€, 50€, 100€, 200€ и 500€, като последният вече не се издава от 2019 г. поради опасения, че улеснява незаконни сделки.",
        "Хитра подробност: монетата от 20 цента има седем заоблени ръба във формата на цвете, за да може да се разпознава на пипане дори в тъмен джоб. Евро монетите също са проектирани да устояват на претопяване, а броячите на пари ги разпознават по тегло и магнитни свойства — именно на този принцип работи и този калкулатор.",
      ],
    },
  },
  usd: {
    nome: "US Dollar ($)",
    bandeira: "🇺🇸",
    flagCode: "us",
    simbolo: "$",
    notas: [1, 5, 10, 20, 50, 100],
    moedas: [0.01, 0.05, 0.1, 0.25, 0.5, 1],
    lang: "en",
    pageTitle: "US Dollar Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the US Dollar",
      paragraphs: [
        "American paper money traces back to the Revolutionary War, when the young United States printed currency to help fund the fight for independence, though those early notes quickly lost most of their value. The dollar bills used today, called Federal Reserve Notes, have been issued since 1914 and became the only type of US currency still in circulation after 1971, when the country stopped tying the dollar's value to gold entirely.",
        "Seven denominations circulate today: $1, $2, $5, $10, $20, $50 and $100. Larger bills once existed, including $500, $1,000, and even a $10,000 note, but they were discontinued in 1969 as electronic banking reduced the need to move large sums in cash. Each denomination carries the portrait of a notable historical figure, George Washington on the $1, Abraham Lincoln on the $5, and so on, a tradition that has held since the early 20th century.",
        "One detail many people never notice: US paper currency isn't actually paper in the usual sense. It's woven from a blend of cotton and linen fibers, which is why a dollar bill can survive a spin in the washing machine far better than an ordinary sheet of paper. That same durability is part of why coins and notes still matter for everyday cash handling, and why a quick counter like this one comes in handy at the register or the end of a shift.",
      ],
    },
  },
  real: {
    nome: "Real (R$)",
    bandeira: "🇧🇷",
    flagCode: "br",
    simbolo: "R$",
    notas: [2, 5, 10, 20, 50, 100, 200],
    moedas: [0.05, 0.1, 0.25, 0.5, 1],
    lang: "pt-BR",
    pageTitle: "Contador de Dinheiro em Reais",
    tagline: "Conte suas notas e moedas em segundos",
    description:
      "Escolha a moeda, informe quantas notas e moedas você tem, e veja o total na hora.",
    searchTerm: "contador de dinheiro",
    ui: {
      coins: "Moedas",
      notes: "Notas",
      total: "Total",
      clear: "Limpar tudo",
      coinsSub: "Subtotal moedas",
      notesSub: "Subtotal notas",
      footer: "conte seu dinheiro em segundos",
    },
    article: {
      heading: "Sobre o Real",
      paragraphs: [
        "O real foi criado em 1994, no meio do Plano Real, um plano econômico pensado para conter uma inflação que, nos anos anteriores, corroía o valor do dinheiro quase todo mês. Antes dele, o Brasil já tinha trocado de moeda várias vezes ao longo do século — cruzeiro, cruzado, cruzado novo — sem conseguir estabilizar os preços. O nome 'real' não é por acaso: em português, a palavra significa tanto 'verdadeiro' quanto remete à antiga moeda real da época colonial.",
        "Hoje circulam notas de R$2, R$5, R$10, R$20, R$50, R$100 e R$200 (esta última lançada só em 2020), além de moedas de 5, 10, 25 e 50 centavos e de 1 real. Uma curiosidade que ajuda a identificar rapidamente cada nota: cada uma tem uma cor diferente e traz, no verso, um animal brasileiro distinto — a tartaruga-de-pente na nota de R$2, a arara-vermelha na de R$10, o mico-leão-dourado na de R$20, a onça-pintada na de R$50, e o lobo-guará na mais recente, de R$200.",
        "As notas também têm tamanhos ligeiramente diferentes de acordo com o valor, uma escolha de design pensada para ajudar pessoas com deficiência visual a diferenciá-las pelo tato. E tem um detalhe que confunde muita gente de fora: no Brasil, os valores são escritos com vírgula em vez de ponto — R$ 10.000,50 em vez de R$ 10,000.50 — o oposto do que é comum em inglês.",
      ],
    },
  },
  libra: {
    nome: "British Pound (£)",
    bandeira: "🇬🇧",
    flagCode: "gb",
    simbolo: "£",
    notas: [5, 10, 20, 50],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "en",
    pageTitle: "British Pound Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the British Pound",
      paragraphs: [
        "Sterling is the oldest currency still in continuous use in the world, with roots going back over 1,200 years. Its name comes from the Latin phrase libra pondo, meaning pound weight, a nod to the era when a coin's value really was tied to how much silver it weighed. The Bank of England has issued pound notes since 1694, and for its first century or so, notes were literally handwritten and signed by a cashier for each individual payment.",
        "Four denominations circulate today: £5, £10, £20 and £50, alongside coins from 1p up to £2. Since 2016, every Bank of England note has been printed on polymer rather than paper, a switch that made them harder to counterfeit and far more resistant to a spin in the washing machine. Each note also carries a portrait on the back honoring a notable figure from British history, Winston Churchill on the £5, Jane Austen on the £10, and codebreaker Alan Turing on the £50.",
        "Notes are gradually shifting again as King Charles III's portrait replaces Queen Elizabeth II's on the front of new notes entering circulation, while older Elizabeth II notes remain valid and continue to circulate alongside them. Whichever monarch or historical figure is on the note in your pocket, this counter handles pounds and pence just as quickly as any other currency.",
      ],
    },
  },
  jpy: {
    nome: "円 (JPY)",
    bandeira: "🇯🇵",
    flagCode: "jp",
    simbolo: "¥",
    notas: [1000, 2000, 5000, 10000],
    moedas: [1, 5, 10, 50, 100, 500],
    lang: "ja",
    pageTitle: "現金計算機",
    tagline: "紙幣と硬貨を数秒で数える",
    description: "通貨を選び、紙幣と硬貨の枚数を入力すると、合計がすぐに表示されます。",
    searchTerm: "現金計算機 / コインカウンター",
    ui: {
      coins: "硬貨",
      notes: "紙幣",
      total: "合計",
      clear: "すべてクリア",
      coinsSub: "硬貨の小計",
      notesSub: "紙幣の小計",
      footer: "数秒でお金を数える",
    },
    article: {
      heading: "円について",
      paragraphs: [
        "円は1871年に導入され、江戸時代までの複雑な藩札制度に代わる統一通貨となりました。「円」という名前は「丸いもの」を意味し、当時の硬貨の形に由来しています。現在流通している紙幣は2024年から新しいデザインに切り替わり、偽造防止のためのホログラム技術が導入されました。1万円札の肖像は渋沢栄一で、日本の資本主義の父と呼ばれる実業家です。",
        "小さな豆知識として、1円硬貨はアルミニウム製で非常に軽く、水に浮くほどです。硬貨は1円、5円、10円、50円、100円、500円の6種類があり、5円硬貨には中央に穴が開いているのが特徴です。このカウンターを使えば、財布や小銭入れの中身を数秒で数えることができます。",
      ],
    },
  },
  peso: {
    nome: "Peso Mexicano ($)",
    bandeira: "🇲🇽",
    flagCode: "mx",
    simbolo: "$",
    notas: [20, 50, 100, 200, 500, 1000],
    moedas: [0.5, 1, 2, 5, 10, 20],
    lang: "es",
    pageTitle: "Contador de Dinero (Peso Mexicano)",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, introduce cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
    article: {
      heading: "Sobre el Peso Mexicano",
      paragraphs: [
        "El peso mexicano tiene raíces que se remontan al peso de plata español colonial, una de las monedas más influyentes del comercio mundial durante siglos. La versión actual se introdujo en 1993, tras quitarle tres ceros al antiguo peso para simplificar las cuentas después de años de alta inflación. Hoy circulan billetes de 20, 50, 100, 200, 500 y 1,000 pesos, cada uno con un diseño distinto dedicado a figuras y paisajes mexicanos, desde Benito Juárez hasta el águila real.",
        "Un detalle curioso: los billetes mexicanos más recientes incluyen ventanas transparentes y tintas que cambian de color al inclinarlos, medidas pensadas para dificultar la falsificación. Las monedas van desde 50 centavos hasta 20 pesos. Contar pesos en efectivo, ya sea en una tienda o al final del día, es justo lo que esta calculadora hace en segundos.",
      ],
    },
  },
  rupee: {
    nome: "Indian Rupee (₹)",
    bandeira: "🇮🇳",
    flagCode: "in",
    simbolo: "₹",
    notas: [10, 20, 50, 100, 200, 500, 2000],
    moedas: [1, 2, 5, 10, 20],
    lang: "en",
    pageTitle: "Indian Rupee Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the Indian Rupee",
      paragraphs: [
        "The Indian rupee's name comes from the Sanskrit word rupya, meaning a shaped or stamped silver coin, and coins bearing that name have circulated on the subcontinent for over two thousand years. The modern rupee is issued by the Reserve Bank of India, and its banknotes carry text in seventeen languages on the reverse side, reflecting India's remarkable linguistic diversity. In 2016, the government abruptly withdrew all 500 and 1,000 rupee notes from circulation overnight in a controversial move aimed at curbing tax evasion and counterfeit currency.",
        "Today's notes run from ₹10 up to ₹2,000, though ₹2,000 notes are being gradually phased out of circulation. Coins range from ₹1 to ₹20. Whether you're counting a stack of notes from a market stall or a till at closing time, this calculator handles rupees just as quickly as any other currency.",
      ],
    },
  },
  cad: {
    nome: "Canadian Dollar ($)",
    bandeira: "🇨🇦",
    flagCode: "ca",
    simbolo: "$",
    notas: [5, 10, 20, 50, 100],
    moedas: [0.05, 0.1, 0.25, 0.5, 1, 2],
    lang: "en",
    pageTitle: "Canadian Dollar Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the Canadian Dollar",
      paragraphs: [
        "The Canadian dollar replaced the Canadian pound in 1858, aligning the currency more closely with the decimal system already used south of the border. Since 2011, all Canadian banknotes have been printed on a durable polymer material instead of paper, making them harder to counterfeit and more resistant to moisture. Canadians have also embraced a distinctly casual vocabulary for their coins: the $1 coin is nicknamed the 'loonie' after the loon bird depicted on it, and the $2 coin is the 'toonie', a playful combination of 'two' and 'loonie'.",
        "Five denominations of notes circulate today: $5, $10, $20, $50 and $100, while coins run from 5 cents up to the $2 toonie. Canada actually discontinued the penny (1 cent coin) back in 2013, so cash transactions are now rounded to the nearest 5 cents. This counter handles all the loonies, toonies, and bills you throw at it in seconds.",
      ],
    },
  },
  php: {
    nome: "Philippine Peso (₱)",
    bandeira: "🇵🇭",
    flagCode: "ph",
    simbolo: "₱",
    notas: [20, 50, 100, 200, 500, 1000],
    moedas: [1, 5, 10, 20],
    lang: "en",
    pageTitle: "Philippine Peso Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / pera counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the Philippine Peso",
      paragraphs: [
        "The Philippine peso traces its roots to the Spanish colonial era, when silver coins from Mexico and Spain circulated throughout the archipelago for centuries. Its modern banknotes, part of the 'New Generation Currency' series introduced in 2010, showcase Filipino national heroes, iconic wildlife, and historical landmarks on each denomination. The ₱1,000 note, for instance, honors three World War II heroes and features the endangered Philippine eagle on its reverse.",
        "Six denominations of notes circulate today, from ₱20 up to ₱1,000, alongside coins ranging from ₱1 to ₱20. Many Filipinos still refer to money informally as 'pera' in everyday conversation, and small businesses and market vendors count cash by hand constantly throughout the day, which is exactly the kind of quick task this calculator is built to speed up.",
      ],
    },
  },
  ars: {
    nome: "Peso Argentino ($)",
    bandeira: "🇦🇷",
    flagCode: "ar",
    simbolo: "$",
    notas: [100, 200, 500, 1000, 2000, 10000],
    moedas: [1, 2, 5, 10, 25, 50],
    lang: "es",
    pageTitle: "Contador de Dinero (Peso Argentino)",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, introduce cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero / contador de billetes",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
    article: {
      heading: "Sobre el Peso Argentino",
      paragraphs: [
        "El peso argentino actual se introdujo en 1992, tras una serie de reformas monetarias en las décadas anteriores que llegaron a incluir hasta trece ceros eliminados de la moneda original debido a episodios de altísima inflación. Los billetes en circulación muestran animales autóctonos de Argentina, como el yaguareté, el cóndor andino y el hornero. Debido a la inflación persistente del país, el Banco Central ha tenido que introducir billetes de denominaciones cada vez más altas, incluyendo el de 10.000 pesos.",
        "Actualmente circulan billetes desde 100 hasta 10.000 pesos, y monedas que van de 1 a 50 pesos, aunque muchas monedas pequeñas prácticamente han dejado de usarse en la práctica diaria. Contar efectivo en pesos argentinos, especialmente con la variedad de denominaciones nuevas y antiguas que aún circulan juntas, es exactamente el tipo de tarea que esta calculadora resuelve en segundos.",
      ],
    },
  },
  ngn: {
    nome: "Nigerian Naira (₦)",
    bandeira: "🇳🇬",
    flagCode: "ng",
    simbolo: "₦",
    notas: [50, 100, 200, 500, 1000],
    moedas: [1, 2, 5, 10, 20, 50],
    lang: "en",
    pageTitle: "Naira Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / naira counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the Nigerian Naira",
      paragraphs: [
        "The naira replaced the Nigerian pound in 1973, taking its name from a shortened form of the word 'Nigeria' itself. Nigeria's central bank has redesigned several denominations over the years, most recently introducing new note designs in late 2022 as part of an effort to combat currency hoarding and counterfeiting. Naira banknotes feature prominent Nigerian historical figures, including independence leaders and cultural icons, printed on each denomination.",
        "Five denominations of notes circulate today, from ₦50 up to ₦1,000, alongside coins from ₦1 to ₦50, though coins are now rarely used in everyday transactions. Cash remains central to daily commerce across Nigeria's markets and small businesses, and counting naira notes quickly and accurately is a genuinely useful everyday task.",
      ],
    },
  },
  yuan: {
    nome: "人民币 (CNY)",
    bandeira: "🇨🇳",
    flagCode: "cn",
    simbolo: "¥",
    notas: [1, 5, 10, 20, 50, 100],
    moedas: [0.1, 0.5, 1],
    lang: "zh",
    pageTitle: "现金计算器",
    tagline: "几秒钟内数清你的纸币和硬币",
    description: "选择货币，输入纸币和硬币的数量，立即查看总额。",
    searchTerm: "现金计算器",
    ui: {
      coins: "硬币",
      notes: "纸币",
      total: "总计",
      clear: "清除全部",
      coinsSub: "硬币小计",
      notesSub: "纸币小计",
      footer: "几秒钟数清你的钱",
    },
    article: {
      heading: "关于人民币",
      paragraphs: [
        "人民币于1948年由中国人民银行发行,人民币意为人民的货币，而其基本单位元则是日常口语中更常用的说法。第五套人民币纸币自1999年起陆续发行，各面额均印有毛泽东的肖像，并采用了多项防伪技术，包括安全线和水印。硬币方面则采用较为简约的设计,常见图案包括牡丹花和菊花。",
        "目前流通的纸币面额从1元到100元不等，硬币则包括1角、5角和1元。由于移动支付在中国的普及率极高，现金的使用比例逐年下降，但在许多小商户、市场摊位以及老一辈人中，现金仍然是日常交易的重要方式。这款计算器正是为快速清点纸币和硬币而设计的实用工具。",
      ],
    },
  },
  rupiah: {
    nome: "Rupiah (Rp)",
    bandeira: "🇮🇩",
    flagCode: "id",
    simbolo: "Rp",
    notas: [1000, 2000, 5000, 10000, 20000, 50000, 100000],
    moedas: [100, 200, 500, 1000],
    lang: "id",
    pageTitle: "Penghitung Uang",
    tagline: "Hitung uang kertas dan koinmu dalam hitungan detik",
    description:
      "Pilih mata uang, masukkan jumlah uang kertas dan koin yang kamu punya, dan lihat totalnya seketika.",
    searchTerm: "penghitung uang tunai",
    ui: {
      coins: "Koin",
      notes: "Uang Kertas",
      total: "Total",
      clear: "Hapus semua",
      coinsSub: "Subtotal koin",
      notesSub: "Subtotal uang kertas",
      footer: "hitung uangmu dalam hitungan detik",
    },
    article: {
      heading: "Tentang Rupiah",
      paragraphs: [
        "Rupiah telah menjadi mata uang resmi Indonesia sejak kemerdekaan pada tahun 1949, menggantikan mata uang zaman kolonial Belanda. Nama rupiah sendiri berasal dari kata rupee, mata uang India yang memengaruhi banyak wilayah Asia Selatan dan Tenggara pada masa lalu. Karena nilai tukarnya yang relatif rendah dibandingkan mata uang utama dunia, uang kertas rupiah memiliki nominal yang sangat besar, dengan pecahan tertinggi mencapai seratus ribu rupiah.",
        "Saat ini beredar uang kertas mulai dari Rp1.000 hingga Rp100.000, serta uang koin dari Rp100 hingga Rp1.000. Bank Indonesia secara rutin memperbarui desain uang kertas dengan menambahkan gambar pahlawan nasional dan pemandangan alam Indonesia di setiap pecahan. Menghitung tumpukan uang tunai dengan berbagai pecahan seperti ini bisa memakan waktu, dan itulah sebabnya kalkulator ini dibuat untuk mempercepat prosesnya.",
      ],
    },
  },
  won: {
    nome: "원 (KRW)",
    bandeira: "🇰🇷",
    flagCode: "kr",
    simbolo: "₩",
    notas: [1000, 5000, 10000, 50000],
    moedas: [10, 50, 100, 500],
    lang: "ko",
    pageTitle: "현금 계산기",
    tagline: "지폐와 동전을 몇 초 만에 세어보세요",
    description: "통화를 선택하고 지폐와 동전의 수를 입력하면 합계가 바로 표시됩니다.",
    searchTerm: "현금 계산기",
    ui: {
      coins: "동전",
      notes: "지폐",
      total: "합계",
      clear: "모두 지우기",
      coinsSub: "동전 소계",
      notesSub: "지폐 소계",
      footer: "몇 초 만에 돈을 세어보세요",
    },
    article: {
      heading: "원화에 대하여",
      paragraphs: [
        "대한민국 원화는 1962년에 현재의 형태로 도입되었으며, 이전의 환을 대체했습니다. 원이라는 이름은 둥근 모양을 뜻하는 한자에서 유래했으며, 이는 동아시아 여러 통화의 공통된 어원이기도 합니다. 현재 유통되는 지폐에는 조선시대의 유명한 학자와 인물들이 그려져 있는데, 그중 5만원권에는 한국 최초의 여성 화가로 알려진 신사임당이 등장합니다.",
        "현재 지폐는 1천원부터 5만원까지 네 종류가 유통되고 있으며, 동전은 10원부터 500원까지 있습니다. 한국은 모바일 결제와 카드 사용이 매우 보편화되어 있지만, 시장이나 소규모 상점에서는 여전히 현금 거래가 활발합니다. 이 계산기는 지폐와 동전을 빠르게 세어 합계를 확인하는 데 유용하게 사용될 수 있습니다.",
      ],
    },
  },
  lira: {
    nome: "Türk Lirası (₺)",
    bandeira: "🇹🇷",
    flagCode: "tr",
    simbolo: "₺",
    notas: [5, 10, 20, 50, 100, 200],
    moedas: [0.05, 0.1, 0.25, 0.5, 1],
    lang: "tr",
    pageTitle: "Nakit Sayma Makinesi",
    tagline: "Banknotlarını ve bozuk paralarını saniyeler içinde say",
    description:
      "Para birimini seç, kaç banknot ve bozuk paran olduğunu gir, toplamı anında gör.",
    searchTerm: "nakit sayma makinesi / para sayacı",
    ui: {
      coins: "Bozuk Para",
      notes: "Banknot",
      total: "Toplam",
      clear: "Hepsini temizle",
      coinsSub: "Bozuk para ara toplamı",
      notesSub: "Banknot ara toplamı",
      footer: "paranı saniyeler içinde say",
    },
    article: {
      heading: "Türk Lirası Hakkında",
      paragraphs: [
        "Türk lirası, Osmanlı İmparatorluğu döneminden bu yana kullanılan bir para birimi adıdır, ancak bugünkü haliyle 2005 yılında büyük bir reformdan geçmiştir. O tarihte, önceki yıllarda yaşanan yüksek enflasyon nedeniyle birikmiş altı sıfır banknotlardan silinerek Yeni Türk Lirası tanıtılmış, ardından 2009'da tekrar sadece Türk Lirası adını almıştır. Banknotların üzerinde, ülkenin kurucusu Mustafa Kemal Atatürk'ün portresi yer almaktadır.",
        "Bugün 5, 10, 20, 50, 100 ve 200 liralık banknotlar ile kuruş cinsinden çeşitli madeni paralar tedavüldedir. Türkiye'de son yıllarda yaşanan yüksek enflasyon nedeniyle nakit sayımı günlük hayatta sıkça karşılaşılan bir ihtiyaç haline gelmiştir; bu hesap makinesi de tam olarak bu ihtiyacı hızlıca karşılamak için tasarlanmıştır.",
      ],
    },
  },
  dong: {
    nome: "Đồng (₫)",
    bandeira: "🇻🇳",
    flagCode: "vn",
    simbolo: "₫",
    notas: [1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000],
    moedas: [],
    lang: "vi",
    pageTitle: "Máy Đếm Tiền",
    tagline: "Đếm tiền giấy của bạn chỉ trong vài giây",
    description:
      "Chọn loại tiền tệ, nhập số lượng tiền giấy bạn có và xem tổng số tiền ngay lập tức.",
    searchTerm: "máy đếm tiền",
    ui: {
      coins: "Tiền xu",
      notes: "Tiền giấy",
      total: "Tổng cộng",
      clear: "Xóa tất cả",
      coinsSub: "Tạm tính tiền xu",
      notesSub: "Tạm tính tiền giấy",
      footer: "đếm tiền của bạn trong vài giây",
    },
    article: {
      heading: "Về Đồng Việt Nam",
      paragraphs: [
        "Đồng Việt Nam đã là đơn vị tiền tệ chính thức của Việt Nam kể từ năm 1978, sau khi thống nhất đất nước. Do lịch sử lạm phát cao trong quá khứ, các mệnh giá tiền giấy hiện nay khá lớn, với tờ tiền có mệnh giá cao nhất lên đến 500.000 đồng. Từ năm 2003, Việt Nam đã chuyển sang in tiền giấy bằng chất liệu polymer thay vì giấy cotton truyền thống, giúp tiền bền hơn và khó làm giả hơn.",
        "Hiện nay, các mệnh giá tiền giấy phổ biến bao gồm từ 1.000 đồng đến 500.000 đồng, và về cơ bản không còn tiền xu lưu hành rộng rãi trong đời sống hằng ngày. Vì mệnh giá tiền khá lớn, việc đếm nhanh và chính xác một xấp tiền là điều rất hữu ích, và đó chính là mục đích của công cụ tính toán này.",
      ],
    },
  },
};

export const DEFAULT_CURRENCY = "eur";

export function getCurrencySlugs() {
  return Object.keys(CURRENCIES);
}

export function getCurrency(slug) {
  return CURRENCIES[slug] || null;
}
