// Configuração de todas as moedas do CashSum.
// A chave do objeto é usada como slug do URL: cashsum.app/[slug]

export const CURRENCIES = {
  eur: {
    nome: "Euro (€)",
    bandeira: "🇪🇺",
    flagCode: "eu",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "en",
    pageTitle: "Euro Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  usd: {
    nome: "US Dollar ($)",
    bandeira: "🇺🇸",
    flagCode: "us",
    simbolo: "$",
    notas: [1, 5, 10, 20, 50, 100],
    moedas: [0.01, 0.05, 0.1, 0.25, 0.5, 1],
    lang: "en",
    pageTitle: "US Dollar Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  real: {
    nome: "Real (R$)",
    bandeira: "🇧🇷",
    flagCode: "br",
    simbolo: "R$",
    notas: [2, 5, 10, 20, 50, 100, 200],
    moedas: [0.05, 0.1, 0.25, 0.5, 1],
    lang: "pt",
    pageTitle: "Contador de Dinheiro em Reais",
    tagline: "Conta as tuas notas e moedas em segundos",
    description:
      "Escolhe a moeda, insere quantas notas e moedas tens, e vê o total na hora.",
    searchTerm: "contador de dinheiro",
    ui: {
      coins: "Moedas",
      notes: "Notas",
      total: "Total",
      clear: "Limpar tudo",
      coinsSub: "Subtotal moedas",
      notesSub: "Subtotal notas",
      footer: "conta o teu dinheiro em segundos",
    },
  },
  libra: {
    nome: "British Pound (£)",
    bandeira: "🇬🇧",
    flagCode: "gb",
    simbolo: "£",
    notas: [5, 10, 20, 50],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "en",
    pageTitle: "British Pound Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  jpy: {
    nome: "円 (JPY)",
    bandeira: "🇯🇵",
    flagCode: "jp",
    simbolo: "¥",
    notas: [1000, 2000, 5000, 10000],
    moedas: [1, 5, 10, 50, 100, 500],
    lang: "ja",
    pageTitle: "現金計算機",
    tagline: "紙幣と硬貨を数秒で数える",
    description: "通貨を選び、紙幣と硬貨の枚数を入力すると、合計がすぐに表示されます。",
    searchTerm: "現金計算機 / コインカウンター",
    ui: {
      coins: "硬貨",
      notes: "紙幣",
      total: "合計",
      clear: "すべてクリア",
      coinsSub: "硬貨の小計",
      notesSub: "紙幣の小計",
      footer: "数秒でお金を数える",
    },
  },
  peso: {
    nome: "Peso Mexicano ($)",
    bandeira: "🇲🇽",
    flagCode: "mx",
    simbolo: "$",
    notas: [20, 50, 100, 200, 500, 1000],
    moedas: [0.5, 1, 2, 5, 10, 20],
    lang: "es",
    pageTitle: "Contador de Dinero (Peso Mexicano)",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, introduce cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
  },
  rupee: {
    nome: "Indian Rupee (₹)",
    bandeira: "🇮🇳",
    flagCode: "in",
    simbolo: "₹",
    notas: [10, 20, 50, 100, 200, 500, 2000],
    moedas: [1, 2, 5, 10, 20],
    lang: "en",
    pageTitle: "Indian Rupee Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  cad: {
    nome: "Canadian Dollar ($)",
    bandeira: "🇨🇦",
    flagCode: "ca",
    simbolo: "$",
    notas: [5, 10, 20, 50, 100],
    moedas: [0.05, 0.1, 0.25, 0.5, 1, 2],
    lang: "en",
    pageTitle: "Canadian Dollar Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  php: {
    nome: "Philippine Peso (₱)",
    bandeira: "🇵🇭",
    flagCode: "ph",
    simbolo: "₱",
    notas: [20, 50, 100, 200, 500, 1000],
    moedas: [1, 5, 10, 20],
    lang: "en",
    pageTitle: "Philippine Peso Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / pera counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  ars: {
    nome: "Peso Argentino ($)",
    bandeira: "🇦🇷",
    flagCode: "ar",
    simbolo: "$",
    notas: [100, 200, 500, 1000, 2000, 10000],
    moedas: [1, 2, 5, 10, 25, 50],
    lang: "es",
    pageTitle: "Contador de Dinero (Peso Argentino)",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, introduce cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero / contador de billetes",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
  },
  ngn: {
    nome: "Nigerian Naira (₦)",
    bandeira: "🇳🇬",
    flagCode: "ng",
    simbolo: "₦",
    notas: [50, 100, 200, 500, 1000],
    moedas: [1, 2, 5, 10, 20, 50],
    lang: "en",
    pageTitle: "Naira Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / naira counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  yuan: {
    nome: "人民币 (CNY)",
    bandeira: "🇨🇳",
    flagCode: "cn",
    simbolo: "¥",
    notas: [1, 5, 10, 20, 50, 100],
    moedas: [0.1, 0.5, 1],
    lang: "zh",
    pageTitle: "现金计算器",
    tagline: "几秒钟内数清你的纸币和硬币",
    description: "选择货币，输入纸币和硬币的数量，立即查看总额。",
    searchTerm: "现金计算器",
    ui: {
      coins: "硬币",
      notes: "纸币",
      total: "总计",
      clear: "清除全部",
      coinsSub: "硬币小计",
      notesSub: "纸币小计",
      footer: "几秒钟数清你的钱",
    },
  },
  rupiah: {
    nome: "Rupiah (Rp)",
    bandeira: "🇮🇩",
    flagCode: "id",
    simbolo: "Rp",
    notas: [1000, 2000, 5000, 10000, 20000, 50000, 100000],
    moedas: [100, 200, 500, 1000],
    lang: "id",
    pageTitle: "Penghitung Uang",
    tagline: "Hitung uang kertas dan koinmu dalam hitungan detik",
    description:
      "Pilih mata uang, masukkan jumlah uang kertas dan koin yang kamu punya, dan lihat totalnya seketika.",
    searchTerm: "penghitung uang tunai",
    ui: {
      coins: "Koin",
      notes: "Uang Kertas",
      total: "Total",
      clear: "Hapus semua",
      coinsSub: "Subtotal koin",
      notesSub: "Subtotal uang kertas",
      footer: "hitung uangmu dalam hitungan detik",
    },
  },
  won: {
    nome: "원 (KRW)",
    bandeira: "🇰🇷",
    flagCode: "kr",
    simbolo: "₩",
    notas: [1000, 5000, 10000, 50000],
    moedas: [10, 50, 100, 500],
    lang: "ko",
    pageTitle: "현금 계산기",
    tagline: "지폐와 동전을 몇 초 만에 세어보세요",
    description: "통화를 선택하고 지폐와 동전의 수를 입력하면 합계가 바로 표시됩니다.",
    searchTerm: "현금 계산기",
    ui: {
      coins: "동전",
      notes: "지폐",
      total: "합계",
      clear: "모두 지우기",
      coinsSub: "동전 소계",
      notesSub: "지폐 소계",
      footer: "몇 초 만에 돈을 세어보세요",
    },
  },
  lira: {
    nome: "Türk Lirası (₺)",
    bandeira: "🇹🇷",
    flagCode: "tr",
    simbolo: "₺",
    notas: [5, 10, 20, 50, 100, 200],
    moedas: [0.05, 0.1, 0.25, 0.5, 1],
    lang: "tr",
    pageTitle: "Nakit Sayma Makinesi",
    tagline: "Banknotlarını ve bozuk paralarını saniyeler içinde say",
    description:
      "Para birimini seç, kaç banknot ve bozuk paran olduğunu gir, toplamı anında gör.",
    searchTerm: "nakit sayma makinesi / para sayacı",
    ui: {
      coins: "Bozuk Para",
      notes: "Banknot",
      total: "Toplam",
      clear: "Hepsini temizle",
      coinsSub: "Bozuk para ara toplamı",
      notesSub: "Banknot ara toplamı",
      footer: "paranı saniyeler içinde say",
    },
  },
  dong: {
    nome: "Đồng (₫)",
    bandeira: "🇻🇳",
    flagCode: "vn",
    simbolo: "₫",
    notas: [1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000],
    moedas: [],
    lang: "vi",
    pageTitle: "Máy Đếm Tiền",
    tagline: "Đếm tiền giấy của bạn chỉ trong vài giây",
    description:
      "Chọn loại tiền tệ, nhập số lượng tiền giấy bạn có và xem tổng số tiền ngay lập tức.",
    searchTerm: "máy đếm tiền",
    ui: {
      coins: "Tiền xu",
      notes: "Tiền giấy",
      total: "Tổng cộng",
      clear: "Xóa tất cả",
      coinsSub: "Tạm tính tiền xu",
      notesSub: "Tạm tính tiền giấy",
      footer: "đếm tiền của bạn trong vài giây",
    },
  },
};

export const DEFAULT_CURRENCY = "eur";

export function getCurrencySlugs() {
  return Object.keys(CURRENCIES);
}

export function getCurrency(slug) {
  return CURRENCIES[slug] || null;
}
