// Configuração de todas as moedas do CashSum.
// A chave do objeto é usada como slug do URL: cashsum.app/[slug]

export const CURRENCIES = {
  eur: {
    nome: "Euro (€)",
    bandeira: "🇪🇺",
    flagCode: "eu",
    simbolo: "€",
    notas: [5, 10, 20, 50, 100, 200, 500],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "en",
    pageTitle: "Euro Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the Euro",
      paragraphs: [
        "The euro became an official currency in 1999, but it stayed invisible for three years, used only for electronic accounting while national currencies like the French franc and German mark remained in people's pockets. Physical notes and coins only entered circulation on 1 January 2002, when they quickly replaced twelve national currencies across the newly formed eurozone. Since then, the eurozone has kept growing, most recently welcoming Bulgaria on 1 January 2026.",
        "Euro banknotes come in seven denominations: €5, €10, €20, €50, €100, €200 and €500, though the €500 note stopped being issued in 2019 over concerns it made illicit transactions too easy. Every note shares the same design across all member countries, showing windows and doorways on the front and bridges on the back, symbolizing openness and connection rather than any single nation's landmarks. Coins are different: each country mints its own design on one side, while the reverse stays common to the whole currency union.",
        "A small but clever detail: the 20 cent coin has seven scalloped edges, shaped like a rounded flower, so people can recognize it by touch alone even in a dark pocket or wallet. Euro coins are also designed to resist melting down for their metal value, and vending machines and cash counters use their weight and magnetic properties to sort them automatically, the same logic this calculator relies on to help you count your euros in seconds.",
      ],
    },
  },
  usd: {
    nome: "US Dollar ($)",
    bandeira: "🇺🇸",
    flagCode: "us",
    simbolo: "$",
    notas: [1, 5, 10, 20, 50, 100],
    moedas: [0.01, 0.05, 0.1, 0.25, 0.5, 1],
    lang: "en",
    pageTitle: "US Dollar Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the US Dollar",
      paragraphs: [
        "American paper money traces back to the Revolutionary War, when the young United States printed currency to help fund the fight for independence, though those early notes quickly lost most of their value. The dollar bills used today, called Federal Reserve Notes, have been issued since 1914 and became the only type of US currency still in circulation after 1971, when the country stopped tying the dollar's value to gold entirely.",
        "Seven denominations circulate today: $1, $2, $5, $10, $20, $50 and $100. Larger bills once existed, including $500, $1,000, and even a $10,000 note, but they were discontinued in 1969 as electronic banking reduced the need to move large sums in cash. Each denomination carries the portrait of a notable historical figure, George Washington on the $1, Abraham Lincoln on the $5, and so on, a tradition that has held since the early 20th century.",
        "One detail many people never notice: US paper currency isn't actually paper in the usual sense. It's woven from a blend of cotton and linen fibers, which is why a dollar bill can survive a spin in the washing machine far better than an ordinary sheet of paper. That same durability is part of why coins and notes still matter for everyday cash handling, and why a quick counter like this one comes in handy at the register or the end of a shift.",
      ],
    },
  },
  real: {
    nome: "Real (R$)",
    bandeira: "🇧🇷",
    flagCode: "br",
    simbolo: "R$",
    notas: [2, 5, 10, 20, 50, 100, 200],
    moedas: [0.05, 0.1, 0.25, 0.5, 1],
    lang: "pt-BR",
    pageTitle: "Contador de Dinheiro em Reais",
    tagline: "Conte suas notas e moedas em segundos",
    description:
      "Escolha a moeda, informe quantas notas e moedas você tem, e veja o total na hora.",
    searchTerm: "contador de dinheiro",
    ui: {
      coins: "Moedas",
      notes: "Notas",
      total: "Total",
      clear: "Limpar tudo",
      coinsSub: "Subtotal moedas",
      notesSub: "Subtotal notas",
      footer: "conte seu dinheiro em segundos",
    },
    article: {
      heading: "Sobre o Real",
      paragraphs: [
        "O real foi criado em 1994, no meio do Plano Real, um plano econômico pensado para conter uma inflação que, nos anos anteriores, corroía o valor do dinheiro quase todo mês. Antes dele, o Brasil já tinha trocado de moeda várias vezes ao longo do século — cruzeiro, cruzado, cruzado novo — sem conseguir estabilizar os preços. O nome 'real' não é por acaso: em português, a palavra significa tanto 'verdadeiro' quanto remete à antiga moeda real da época colonial.",
        "Hoje circulam notas de R$2, R$5, R$10, R$20, R$50, R$100 e R$200 (esta última lançada só em 2020), além de moedas de 5, 10, 25 e 50 centavos e de 1 real. Uma curiosidade que ajuda a identificar rapidamente cada nota: cada uma tem uma cor diferente e traz, no verso, um animal brasileiro distinto — a tartaruga-de-pente na nota de R$2, a arara-vermelha na de R$10, o mico-leão-dourado na de R$20, a onça-pintada na de R$50, e o lobo-guará na mais recente, de R$200.",
        "As notas também têm tamanhos ligeiramente diferentes de acordo com o valor, uma escolha de design pensada para ajudar pessoas com deficiência visual a diferenciá-las pelo tato. E tem um detalhe que confunde muita gente de fora: no Brasil, os valores são escritos com vírgula em vez de ponto — R$ 10.000,50 em vez de R$ 10,000.50 — o oposto do que é comum em inglês.",
      ],
    },
  },
  libra: {
    nome: "British Pound (£)",
    bandeira: "🇬🇧",
    flagCode: "gb",
    simbolo: "£",
    notas: [5, 10, 20, 50],
    moedas: [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2],
    lang: "en",
    pageTitle: "British Pound Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
    article: {
      heading: "About the British Pound",
      paragraphs: [
        "Sterling is the oldest currency still in continuous use in the world, with roots going back over 1,200 years. Its name comes from the Latin phrase libra pondo, meaning pound weight, a nod to the era when a coin's value really was tied to how much silver it weighed. The Bank of England has issued pound notes since 1694, and for its first century or so, notes were literally handwritten and signed by a cashier for each individual payment.",
        "Four denominations circulate today: £5, £10, £20 and £50, alongside coins from 1p up to £2. Since 2016, every Bank of England note has been printed on polymer rather than paper, a switch that made them harder to counterfeit and far more resistant to a spin in the washing machine. Each note also carries a portrait on the back honoring a notable figure from British history, Winston Churchill on the £5, Jane Austen on the £10, and codebreaker Alan Turing on the £50.",
        "Notes are gradually shifting again as King Charles III's portrait replaces Queen Elizabeth II's on the front of new notes entering circulation, while older Elizabeth II notes remain valid and continue to circulate alongside them. Whichever monarch or historical figure is on the note in your pocket, this counter handles pounds and pence just as quickly as any other currency.",
      ],
    },
  },
  jpy: {
    nome: "円 (JPY)",
    bandeira: "🇯🇵",
    flagCode: "jp",
    simbolo: "¥",
    notas: [1000, 2000, 5000, 10000],
    moedas: [1, 5, 10, 50, 100, 500],
    lang: "ja",
    pageTitle: "現金計算機",
    tagline: "紙幣と硬貨を数秒で数える",
    description: "通貨を選び、紙幣と硬貨の枚数を入力すると、合計がすぐに表示されます。",
    searchTerm: "現金計算機 / コインカウンター",
    ui: {
      coins: "硬貨",
      notes: "紙幣",
      total: "合計",
      clear: "すべてクリア",
      coinsSub: "硬貨の小計",
      notesSub: "紙幣の小計",
      footer: "数秒でお金を数える",
    },
  },
  peso: {
    nome: "Peso Mexicano ($)",
    bandeira: "🇲🇽",
    flagCode: "mx",
    simbolo: "$",
    notas: [20, 50, 100, 200, 500, 1000],
    moedas: [0.5, 1, 2, 5, 10, 20],
    lang: "es",
    pageTitle: "Contador de Dinero (Peso Mexicano)",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, introduce cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
  },
  rupee: {
    nome: "Indian Rupee (₹)",
    bandeira: "🇮🇳",
    flagCode: "in",
    simbolo: "₹",
    notas: [10, 20, 50, 100, 200, 500, 2000],
    moedas: [1, 2, 5, 10, 20],
    lang: "en",
    pageTitle: "Indian Rupee Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / money counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  cad: {
    nome: "Canadian Dollar ($)",
    bandeira: "🇨🇦",
    flagCode: "ca",
    simbolo: "$",
    notas: [5, 10, 20, 50, 100],
    moedas: [0.05, 0.1, 0.25, 0.5, 1, 2],
    lang: "en",
    pageTitle: "Canadian Dollar Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  php: {
    nome: "Philippine Peso (₱)",
    bandeira: "🇵🇭",
    flagCode: "ph",
    simbolo: "₱",
    notas: [20, 50, 100, 200, 500, 1000],
    moedas: [1, 5, 10, 20],
    lang: "en",
    pageTitle: "Philippine Peso Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / pera counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  ars: {
    nome: "Peso Argentino ($)",
    bandeira: "🇦🇷",
    flagCode: "ar",
    simbolo: "$",
    notas: [100, 200, 500, 1000, 2000, 10000],
    moedas: [1, 2, 5, 10, 25, 50],
    lang: "es",
    pageTitle: "Contador de Dinero (Peso Argentino)",
    tagline: "Cuenta tus billetes y monedas en segundos",
    description:
      "Elige la moneda, introduce cuántos billetes y monedas tienes, y ve el total al instante.",
    searchTerm: "contador de dinero / contador de billetes",
    ui: {
      coins: "Monedas",
      notes: "Billetes",
      total: "Total",
      clear: "Borrar todo",
      coinsSub: "Subtotal monedas",
      notesSub: "Subtotal billetes",
      footer: "cuenta tu dinero en segundos",
    },
  },
  ngn: {
    nome: "Nigerian Naira (₦)",
    bandeira: "🇳🇬",
    flagCode: "ng",
    simbolo: "₦",
    notas: [50, 100, 200, 500, 1000],
    moedas: [1, 2, 5, 10, 20, 50],
    lang: "en",
    pageTitle: "Naira Cash Counter",
    tagline: "Count your notes and coins in seconds",
    description:
      "Pick a currency, enter how many notes and coins you have, and see the total instantly.",
    searchTerm: "cash counter / naira counter",
    ui: {
      coins: "Coins",
      notes: "Notes",
      total: "Total",
      clear: "Clear all",
      coinsSub: "Coins subtotal",
      notesSub: "Notes subtotal",
      footer: "count your money in seconds",
    },
  },
  yuan: {
    nome: "人民币 (CNY)",
    bandeira: "🇨🇳",
    flagCode: "cn",
    simbolo: "¥",
    notas: [1, 5, 10, 20, 50, 100],
    moedas: [0.1, 0.5, 1],
    lang: "zh",
    pageTitle: "现金计算器",
    tagline: "几秒钟内数清你的纸币和硬币",
    description: "选择货币，输入纸币和硬币的数量，立即查看总额。",
    searchTerm: "现金计算器",
    ui: {
      coins: "硬币",
      notes: "纸币",
      total: "总计",
      clear: "清除全部",
      coinsSub: "硬币小计",
      notesSub: "纸币小计",
      footer: "几秒钟数清你的钱",
    },
  },
  rupiah: {
    nome: "Rupiah (Rp)",
    bandeira: "🇮🇩",
    flagCode: "id",
    simbolo: "Rp",
    notas: [1000, 2000, 5000, 10000, 20000, 50000, 100000],
    moedas: [100, 200, 500, 1000],
    lang: "id",
    pageTitle: "Penghitung Uang",
    tagline: "Hitung uang kertas dan koinmu dalam hitungan detik",
    description:
      "Pilih mata uang, masukkan jumlah uang kertas dan koin yang kamu punya, dan lihat totalnya seketika.",
    searchTerm: "penghitung uang tunai",
    ui: {
      coins: "Koin",
      notes: "Uang Kertas",
      total: "Total",
      clear: "Hapus semua",
      coinsSub: "Subtotal koin",
      notesSub: "Subtotal uang kertas",
      footer: "hitung uangmu dalam hitungan detik",
    },
  },
  won: {
    nome: "원 (KRW)",
    bandeira: "🇰🇷",
    flagCode: "kr",
    simbolo: "₩",
    notas: [1000, 5000, 10000, 50000],
    moedas: [10, 50, 100, 500],
    lang: "ko",
    pageTitle: "현금 계산기",
    tagline: "지폐와 동전을 몇 초 만에 세어보세요",
    description: "통화를 선택하고 지폐와 동전의 수를 입력하면 합계가 바로 표시됩니다.",
    searchTerm: "현금 계산기",
    ui: {
      coins: "동전",
      notes: "지폐",
      total: "합계",
      clear: "모두 지우기",
      coinsSub: "동전 소계",
      notesSub: "지폐 소계",
      footer: "몇 초 만에 돈을 세어보세요",
    },
  },
  lira: {
    nome: "Türk Lirası (₺)",
    bandeira: "🇹🇷",
    flagCode: "tr",
    simbolo: "₺",
    notas: [5, 10, 20, 50, 100, 200],
    moedas: [0.05, 0.1, 0.25, 0.5, 1],
    lang: "tr",
    pageTitle: "Nakit Sayma Makinesi",
    tagline: "Banknotlarını ve bozuk paralarını saniyeler içinde say",
    description:
      "Para birimini seç, kaç banknot ve bozuk paran olduğunu gir, toplamı anında gör.",
    searchTerm: "nakit sayma makinesi / para sayacı",
    ui: {
      coins: "Bozuk Para",
      notes: "Banknot",
      total: "Toplam",
      clear: "Hepsini temizle",
      coinsSub: "Bozuk para ara toplamı",
      notesSub: "Banknot ara toplamı",
      footer: "paranı saniyeler içinde say",
    },
  },
  dong: {
    nome: "Đồng (₫)",
    bandeira: "🇻🇳",
    flagCode: "vn",
    simbolo: "₫",
    notas: [1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000],
    moedas: [],
    lang: "vi",
    pageTitle: "Máy Đếm Tiền",
    tagline: "Đếm tiền giấy của bạn chỉ trong vài giây",
    description:
      "Chọn loại tiền tệ, nhập số lượng tiền giấy bạn có và xem tổng số tiền ngay lập tức.",
    searchTerm: "máy đếm tiền",
    ui: {
      coins: "Tiền xu",
      notes: "Tiền giấy",
      total: "Tổng cộng",
      clear: "Xóa tất cả",
      coinsSub: "Tạm tính tiền xu",
      notesSub: "Tạm tính tiền giấy",
      footer: "đếm tiền của bạn trong vài giây",
    },
  },
};

export const DEFAULT_CURRENCY = "eur";

export function getCurrencySlugs() {
  return Object.keys(CURRENCIES);
}

export function getCurrency(slug) {
  return CURRENCIES[slug] || null;
}
